services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '5173:3000'
    volumes:
      - ./frontend:/usr/src/app/frontend
      - /usr/src/app/frontend/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:8085:3010
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/blog-app
      - SECRET_KEY=DONOTUSETHISVALUEINSTEADCREATEACOMPLEXSECRETANDKEEPITSAFEOUTSIDEOFTHESOURCECODE
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
